import "./globals.css";
import Nav from "@/components/Nav";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Exo_2 } from "next/font/google";

const exo = Exo_2({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App Router",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={inter.className}>
      <Nav />
      {children}
      <Footer />
    </div>
  );
}
