import "./globals.css";
import Format from "@/components/Format";

export const metadata = {
  title: "Readable Blog",
  description: "Generated by @scriptwithahmad",

};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.css"
          integrity="sha512-tx5+1LWHez1QiaXlAyDwzdBTfDjX07GMapQoFTS74wkcPMsI3So0KYmFe6EHZjI8+eSG0ljBlAQc3PQ5BTaZtQ=="
        />
        <link rel="icon" href="https://res.cloudinary.com/dmyrswz0r/image/upload/v1713427098/blog-image/favicon_jcqo9l.png" sizes="any" />
      </head>
      <body suppressHydrationWarning={true}>
        <Format>{children}</Format>
      </body>
    </html>
  );
}
