import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { Open_Sans, Merienda } from "next/font/google";

const sans = Open_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog App :: App Router",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.css"
          integrity="sha512-tx5+1LWHez1QiaXlAyDwzdBTfDjX07GMapQoFTS74wkcPMsI3So0KYmFe6EHZjI8+eSG0ljBlAQc3PQ5BTaZtQ=="
        />
      </head>
      <body suppressHydrationWarning={true}>
        <div className={sans.className}>
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
